# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Yarn
      run: npm install -g yarn

    - name: Install PM2 globally
      run: npm install -g pm2

    - name: Install dependencies with Yarn
      run: yarn install --frozen-lockfile

    - name: restart the project with PM2
      run: |
          if pm2 describe dashboard > /dev/null; then
            pm2 restart dashboard --update-env
          else
            pm2 start yarn --name dashboard -- run dev
          fi

    - name: Save PM2 process list
      run: pm2 save
